//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDomain.Phrases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppPhrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppPhrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppDomain.Phrases.AppPhrases", typeof(AppPhrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the new competition data to the repository..
        /// </summary>
        public static string CompetitionDataCreateError {
            get {
                return ResourceManager.GetString("CompetitionDataCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a data of competition from the repository..
        /// </summary>
        public static string CompetitionDataLoadError {
            get {
                return ResourceManager.GetString("CompetitionDataLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove the competition data from the repository..
        /// </summary>
        public static string CompetitionDataRemoveError {
            get {
                return ResourceManager.GetString("CompetitionDataRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the competition data to the repository..
        /// </summary>
        public static string CompetitionDataSaveError {
            get {
                return ResourceManager.GetString("CompetitionDataSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a competition statuses from the repository..
        /// </summary>
        public static string CompetitionsStatusesLoadError {
            get {
                return ResourceManager.GetString("CompetitionsStatusesLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is rebuilt again..
        /// </summary>
        public static string DatabaseRebuilt {
            get {
                return ResourceManager.GetString("DatabaseRebuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a competition statuses and names from the repository..
        /// </summary>
        public static string DetailedCompetitionStatusesLoadError {
            get {
                return ResourceManager.GetString("DetailedCompetitionStatusesLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more Library entities are missing..
        /// </summary>
        public static string MissingEntitiesError {
            get {
                return ResourceManager.GetString("MissingEntitiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add referee to list..
        /// </summary>
        public static string RefereeAddError {
            get {
                return ResourceManager.GetString("RefereeAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the referee job titles from the repository..
        /// </summary>
        public static string RefereeJobTitleFindError {
            get {
                return ResourceManager.GetString("RefereeJobTitleFindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a list of referee job titles from the repository..
        /// </summary>
        public static string RefereeJobTitlesLoadError {
            get {
                return ResourceManager.GetString("RefereeJobTitlesLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the referee level from the repository..
        /// </summary>
        public static string RefereeLevelFindError {
            get {
                return ResourceManager.GetString("RefereeLevelFindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a list of referee levels from the repository..
        /// </summary>
        public static string RefereeLevelsLoadError {
            get {
                return ResourceManager.GetString("RefereeLevelsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove the referee from the repository..
        /// </summary>
        public static string RefereeRemoveError {
            get {
                return ResourceManager.GetString("RefereeRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a list of referee from the repository..
        /// </summary>
        public static string RefereesLoadError {
            get {
                return ResourceManager.GetString("RefereesLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the list of referee to the repository..
        /// </summary>
        public static string RefereesSaveError {
            get {
                return ResourceManager.GetString("RefereesSaveError", resourceCulture);
            }
        }
    }
}
