//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDomain.Phrases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppPhrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppPhrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppDomain.Phrases.AppPhrases", typeof(AppPhrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the application directories..
        /// </summary>
        public static string AppDirsCreateError {
            get {
                return ResourceManager.GetString("AppDirsCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the new competition in the repository..
        /// </summary>
        public static string CompetitionDataCreateError {
            get {
                return ResourceManager.GetString("CompetitionDataCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The competition is missing..
        /// </summary>
        public static string CompetitionDataIsNull {
            get {
                return ResourceManager.GetString("CompetitionDataIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the list of competition from the repository..
        /// </summary>
        public static string CompetitionDataListLoadError {
            get {
                return ResourceManager.GetString("CompetitionDataListLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the competition from the repository..
        /// </summary>
        public static string CompetitionDataLoadError {
            get {
                return ResourceManager.GetString("CompetitionDataLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The competition was not found  in the repository..
        /// </summary>
        public static string CompetitionDataNotFound {
            get {
                return ResourceManager.GetString("CompetitionDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove the competition from the repository..
        /// </summary>
        public static string CompetitionDataRemoveError {
            get {
                return ResourceManager.GetString("CompetitionDataRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the competition to the repository..
        /// </summary>
        public static string CompetitionDataSaveError {
            get {
                return ResourceManager.GetString("CompetitionDataSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the list of competition statuses in the repository..
        /// </summary>
        public static string CompetitionStatusesLoadError {
            get {
                return ResourceManager.GetString("CompetitionStatusesLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the competition status in the repository..
        /// </summary>
        public static string CompetitionStatusFindError {
            get {
                return ResourceManager.GetString("CompetitionStatusFindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the new event organizer..
        /// </summary>
        public static string ConductingOrganizationCreateError {
            get {
                return ResourceManager.GetString("ConductingOrganizationCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove a event organizer..
        /// </summary>
        public static string ConductingOrganizationRemoveError {
            get {
                return ResourceManager.GetString("ConductingOrganizationRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the list of event organizers..
        /// </summary>
        public static string ConductingOrganizationsLoadError {
            get {
                return ResourceManager.GetString("ConductingOrganizationsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set a event organizers..
        /// </summary>
        public static string ConductingOrganizationsSetError {
            get {
                return ResourceManager.GetString("ConductingOrganizationsSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database creation error..
        /// </summary>
        public static string DatabaseCreateError {
            get {
                return ResourceManager.GetString("DatabaseCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is rebuilt again..
        /// </summary>
        public static string DatabaseRebuilt {
            get {
                return ResourceManager.GetString("DatabaseRebuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the list of competition statuses and names from the repository..
        /// </summary>
        public static string DetailedCompetitionStatusesLoadError {
            get {
                return ResourceManager.GetString("DetailedCompetitionStatusesLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the detailed competitions status in the repository..
        /// </summary>
        public static string DetailedCompetitionStatusFindError {
            get {
                return ResourceManager.GetString("DetailedCompetitionStatusFindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the list of discipline groups from the repository..
        /// </summary>
        public static string DisciplineGroupsLoadError {
            get {
                return ResourceManager.GetString("DisciplineGroupsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the discipline from the repository..
        /// </summary>
        public static string DisciplineLoadError {
            get {
                return ResourceManager.GetString("DisciplineLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the list of disciplines from the repository..
        /// </summary>
        public static string DisciplinesLoadError {
            get {
                return ResourceManager.GetString("DisciplinesLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the list of discipline subgroups from the repository..
        /// </summary>
        public static string DisciplineSubGroupsLoadError {
            get {
                return ResourceManager.GetString("DisciplineSubGroupsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizing &quot;{0}&quot; view error..
        /// </summary>
        public static string LocalizingError {
            get {
                return ResourceManager.GetString("LocalizingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more Library entities are missing..
        /// </summary>
        public static string MissingEntitiesError {
            get {
                return ResourceManager.GetString("MissingEntitiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the new referee in the repository..
        /// </summary>
        public static string RefereeCreateError {
            get {
                return ResourceManager.GetString("RefereeCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the referee job titles in the repository..
        /// </summary>
        public static string RefereeJobTitleFindError {
            get {
                return ResourceManager.GetString("RefereeJobTitleFindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a list of referee job titles from the repository..
        /// </summary>
        public static string RefereeJobTitlesLoadError {
            get {
                return ResourceManager.GetString("RefereeJobTitlesLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the referee level in the repository..
        /// </summary>
        public static string RefereeLevelFindError {
            get {
                return ResourceManager.GetString("RefereeLevelFindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the list of referee levels from the repository..
        /// </summary>
        public static string RefereeLevelsLoadError {
            get {
                return ResourceManager.GetString("RefereeLevelsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove the referee from the repository..
        /// </summary>
        public static string RefereeRemoveError {
            get {
                return ResourceManager.GetString("RefereeRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the list of referees from the repository..
        /// </summary>
        public static string RefereesLoadError {
            get {
                return ResourceManager.GetString("RefereesLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the new sport event in the repository..
        /// </summary>
        public static string SportEventCreateError {
            get {
                return ResourceManager.GetString("SportEventCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove the sport event from the repository..
        /// </summary>
        public static string SportEventRemoveError {
            get {
                return ResourceManager.GetString("SportEventRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the list of sport events from the repository..
        /// </summary>
        public static string SportEventsLoadError {
            get {
                return ResourceManager.GetString("SportEventsLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error. For more information, see the log file..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
