name: Auto Sync Created Date to Project

on:
  issues:
    types: [opened, reopened] # Срабатывает автоматически, когда создается новая задача

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
